# -*- coding: utf-8 -*-
"""1WN24CS039_Week_1_Tic_Tac_Toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rGQGWRTkGYWdBLt2lFogtOod2_-le-z
"""

board_initial = [' ' for _ in range(9)]

def display_board(board):
    print('-------------')
    print(f'| {board[0]} | {board[1]} | {board[2]} |')
    print('-------------')
    print(f'| {board[3]} | {board[4]} | {board[5]} |')
    print('-------------')
    print(f'| {board[6]} | {board[7]} | {board[8]} |')
    print('-------------')


def check_win(board, player):

    for i in range(0, 9, 3):
        if board[i] == board[i+1] == board[i+2] == player:
            return True

    for i in range(3):
        if board[i] == board[i+3] == board[i+6] == player:
            return True

    if board[0] == board[4] == board[8] == player:
        return True
    if board[2] == board[4] == board[6] == player:
        return True
    return False


def check_draw(board):
    return ' ' not in board


def player_move(board, player):
    while True:
        try:
            move = int(input(f"Player {player}, enter your move (1-9): ")) - 1
            if 0 <= move < 9 and board[move] == ' ':
                board[move] = player
                break
            else:
                print("Invalid move. Try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")

def play_game(initial_board=None):
    game_board = initial_board if initial_board else [' ' for _ in range(9)]
    current_player = 'X'
    game_over = False

    print("Tic-tac-Toe")
    display_board(game_board)

    while not game_over:
        player_move(game_board, current_player)
        display_board(game_board)

        if check_win(game_board, current_player):
            print(f"Player {current_player} wins!")
            game_over = True
        elif check_draw(game_board):
            print("It's a draw!")
            game_over = True
        else:
            current_player = 'O' if current_player == 'X' else 'X'



custom_initial_board = ['O', ' ', 'X', 'X', ' ', ' ', 'X', 'O', 'O']

play_game(initial_board=custom_initial_board)